version: '3'

services:
  angular-d3-responsive-graph:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: 'angular-d3-responsive-graph'
    command: sh -c "ng serve --host 0.0.0.0 --port 4200"
    ports:
      - "4200:4200"
      - "9876:9876"
    # Automatically hot reload code changes in the Docker container
    volumes:
      - ./:/app
      - ./src:/app/src
